#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

apt-get update
apt-get apt-get install -y --no-install-recommends \
    libturbojpeg0 \
    libpcap-dev

python3 -m pip install --requirement requirements.txt
pre-commit install
