name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      #- name: Get version
      #  id: version
      #  uses: home-assistant/actions/helpers/version@master

      #- name: "Set version number"
      #  run: |
      #    sed -i "/MINIMUM_HA_VERSION = /c\MINIMUM_HA_VERSION = \"$(jq .homeassistant -r ${{ github.workspace }}/hacs.json)\"" ${{ github.workspace }}/custom_components/hacs/const.py
      #    python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}


      # Pack the Sentio dir as a zip and upload to the release
      - name: ZIP Sentio Dir
        run: |
          cd ${{ github.workspace }}/custom_components/sentio
          zip sentio.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/sentio/sentio.zip
          asset_name: sentio.zip
          tag: ${{ github.ref }}
          overwrite: true
